me: "Gregory M. Kapfhammer"
description: "Associate Professor of Computer Science"

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: true
category-list: [main, teaching, research]
excerpt_separator: <!--more-->
mapped: false 
header: false 
research: false 
paper: false
presentation: false
max_header: 8
max_id: 45

