me: "Gregory M. Kapfhammer"
description: "Associate Professor of Computer Science"
baseurl: "/sites/gkapfham/"
markdown: rdiscount
permalink: pretty
highlighter: pygments
category-list: [teaching, research]
excerpt_separator: <!--more-->
mapped: false 
header: false 
research: false 
paper: false
presentation: false
id: 0
max_header: 8
max_id: 45

