me: "Gregory M. Kapfhammer"
description: "Associate Professor of Computer Science"
baseurl: "/sites/gkapfham/"
markdown: rdiscount
permalink: pretty
highlighter: rouge
category-list: [teaching, research]
gems: ['jekyll/scholar']
exclude: ['*.tex', '*.sty', '*.aux', '*.dvi', '*.fls', '*.lof', '*.log', '*.lot', '*.out', '*.toc', '*.fdb_latexmk', '*.synctex.gz', '*.pdfsync', '*.ods', '**/**/**/exams', '**/**/**/logos', '**/**/**/figures', '**/**/**/code', '**/**/**/teams']
excerpt_separator: <!--more-->
mapped: false
header: false
research: false
paper: false
presentation: false
featured: false
id: 0
max_header: 9
max_id: 45

