me: "Gregory M. Kapfhammer"
description: "Associate Professor of Computer Science"

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: /:categories/:title.html 
highlighter: true
category-list: [site, teaching, research]
